[package]
name = "mould"
version = "0.0.1"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
description = "Web-framework for websocket based web-apps."

[dependencies]
log = "~0.3"
env_logger = "~0.3"
rustc-serialize = "~0.3"
#mime = "~0.1"
hyper = "~0.6"
websocket = "~0.12"
