[package]
name = "mould"
version = "0.0.7"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
description = "Rust web-framework for websocket based web-apps."
repository = "https://github.com/DenisKolodin/mould"
license = "MIT"

[dependencies]
log = "~0.3"
rustc-serialize = "~0.3"
hyper = "~0.6.16"
websocket = "~0.12.2"
json_macro = "~0.1.1"