[package]
name = "mould"
version = "0.0.19"
readme = "README.md"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
description = "Rust web-framework for websocket based web-apps."
repository = "https://github.com/DenisKolodin/mould"
license = "MIT/Apache-2.0"

[features]
default = ["iomould", "wsmould"]
iomould = []
wsmould = ["hyper", "websocket"]

[dependencies]
log = "0.3.7"
rustc-serialize = "0.3.19"
slab = "0.3.0"
hyper = { version = "0.10.5", optional = true }
websocket = { git = "https://github.com/cyderize/rust-websocket", optional = true }
