[package]
name = "mould"
version = "0.0.16"
readme = "README.md"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
description = "Rust web-framework for websocket based web-apps."
repository = "https://github.com/DenisKolodin/mould"
license = "MIT/Apache-2.0"

[dependencies]
log = "~0.3.6"
rustc-serialize = "~0.3.19"
hyper = "~0.9.10"
websocket = "~0.17.1"
