[package]
name = "mould"
version = "0.0.7"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
description = "Rust web-framework for websocket based web-apps."
repository = "https://github.com/DenisKolodin/mould"
license = "MIT"

[dependencies]
log = "~0.3.4"
rustc-serialize = "~0.3.16"
hyper = "~0.7.0"
websocket = { git = "https://github.com/cyderize/rust-websocket" } # "~0.14.0"
json_macro = "~0.1.1"